### ISSUE TITLE
[Doc]: Separate public interface from internals

### ISSUE THREAD

**Issue by jariji** [Seelengrab/Supposition.jl#27]
### Which part of the documentation is this related to?

https://seelengrab.github.io/Supposition.jl/dev/interfaces.html
https://seelengrab.github.io/Supposition.jl/dev/api.html

### How could this be communicated better?

I don't like a design where there's an "API" that's not supported. If you want to document internals, that's great, but imho it belongs on a devdocs/internals page, not on the same page with the public `Data` stuff. 

Currently it's something like

- Public macros and functions
- Public Data generators and internals

I suggest

- Public macros and functions
- Public Data generators
- Devdocs/Internals

**Comment by Seelengrab** [comment]
I'm not going to remove the section from the full API reference; it's not a devdocs section after all, I'll add that at a later point. The purpose of that page is to be a full reference of everything on one page.

Fixed in 215a00400cc2d85daac944b1165519b8b4167a26
