### ISSUE TITLE
[UX]: Checking `Vectors(Integers())` property takes too long

### ISSUE THREAD

**Issue by jariji** [Seelengrab/Supposition.jl#43]
### What happened?

Checking this runs for a long time at 100% CPU until I interrupt it after a few minutes.

```jl
using Supposition

# cartesianProductWith
cpw(f, as, bs) = [f(a,b) for a in as for b in bs];

# zipWith
zw(f, as, bs) = [f(a,b) for (a,b) in zip(as,bs)];

V = Data.Vectors(Data.Integers{Int64}())
Supposition.@check function dist(as=V, bs=V, cs=V) 
      cpw(*, as, zw(+, bs, cs)) ≈ zw(+, cpw(*, as, bs), cpw(*, as, cs))
end
```

### How could this be communicated better?

Make it faster or give up sooner?

### Julia Version

```shell
julia> versioninfo()
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 24 × AMD Ryzen 9 3900XT 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver2)
  Threads: 17 on 24 virtual cores
Environment:
  JULIA_NUM_THREADS = 12
```

### Package Environment

```shell
Supposition v0.3.3
```

**Comment by Seelengrab** [comment]
You can limit the size of the generated objects by passing the `max_size` keyword to `Data.Vectors`. In addition, you can limit the number of examples tried by `@check` by passing `max_examples` to it as a keyword, like `@check max_examples=500 function ...`.

There is no general solution here, as different settings will be ideal for different use cases.
